# Generated by Django 4.2.7 on 2023-11-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_category', models.CharField(max_length=100)),
                ('movie_desc', models.TextField()),
                ('in_homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
